### ISSUE TITLE
4th bot

### ISSUE THREAD

**Issue by rrbailey89** [lookapanda/discordcleverbot#1]
The app won't run a 4th bot it seems. It will start then when it's that bots turn it just waits and keeps displaying >1M

**Comment by Ponjimon** [comment]
I will test that tomorrow if I think of it :P

**Comment by rrbailey89** [comment]
> I will test that tomorrow if I think of it :P

I actually already fixed this issue. you must start a new text channel. It seems if you have a chat going. stop it and add the 4th bot the 4th bot will never talk. But if you begin buy using a new text channel it works just fine.

**Comment by Ponjimon** [comment]
well, that shouldn't be. The way the bot works allows it for an indefinite amount of bots to work and be added :/

**Comment by pforpho** [comment]
@rrbailey89 does the bot still work for you? I'm getting

```
D:\Discord Bot\Cleverbot\node_modules\discord.io\lib\index.js:182
                time = (input.message.length * 0.12) * 1000;
                     ^

ReferenceError: time is not defined
    at DiscordClient.DCP.sendMessage (D:\Discord Bot\Cleverbot\node_modules\disc
ord.io\lib\index.js:182:8)
    at null._onTimeout (D:\Discord Bot\Cleverbot\app.js:163:15)
    at Timer.listOnTimeout (timers.js:92:15)

```

**Comment by Ponjimon** [comment]
I suppose that the Discord API got updated and the discord.io library is outdated. 
I will look into it.

**Comment by Ponjimon** [comment]
@pforpho Duplicate of your issue #2 

I'm closing this issue because it's no more relevant. (we figured that out in private)
